### ISSUE TITLE
Please provide AppImage for download

### ISSUE THREAD

**Issue by probonopd** [tgambet/musicalypse#1]
Please provide an AppImage for download.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

`electron-builder` can do AppImages easily.
If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by tgambet** [comment]
Hi @probonopd,
Thank you for the suggestion. I generated an AppImage for my project and made it available for download on the website: https://musicalypse.creasource.net

I built on Ubuntu 18.04 x64 and tested on Ubuntu 14.04 x64 and it looks like it is working fine.

I have however an icon issue when running on Ubuntu 18.04; specifically the dock icon doesn't show. I think that may be an issue with `electron-builder`.

Other than that it wasn't too difficult to get it to work. Congratulations on your work with AppImage.

**Comment by probonopd** [comment]
Thank you very much, it is working well. I think you need to set the icon of the main window so that the icon shows correctly in the dock. On Qt this is done using `QApplication::setWindowIcon()` and I assume there is an Electron equivalent.
